version: '3.8'

services:
  mariadb:
    image: mariadb:11.7.1-noble-rc
    container_name: mariadb_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prjspring2025
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./data:/data
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
